version: '0.2.{build}'

image: Visual Studio 2017

install:
  - ps: Start-FileDownload 'https://github.com/Masterminds/glide/releases/download/v0.12.3/glide-v0.12.3-windows-amd64.zip'
  - ps: expand-archive -Path glide-v0.12.3-windows-amd64.zip
  - ps: $env:PATH
  - ps: copy-item .\glide-v0.12.3-windows-amd64\windows-amd64\glide.exe .\glide.exe

matrix:
  fast_finish: true

branches:
  only:
    - master

#---------------------------------#
#       tests configuration       #
#---------------------------------#

before_test:
  - ps: .\glide.exe up

test_script:
  - ps: go test --coverprofile=cover.cov

#---------------------------------#
#       build configuration       #
#---------------------------------#

before_build:
  - ps: glide up

build_script:
  - ps: go build  -ldflags "-X main.version=$version" -o "build/spinner$version.exe"

after_build:
  - ps: Compress-Archive -Path "build/spinner$version.exe" -Destination "build/spinner$version.zip"

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:

  # pushing a single file
  - path: build/spinner$(version).zip
    name: zip

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

deploy:
  - provider: GitHub
    release: myproduct-v$(appveyor_build_version)
    description: 'Automated Release'
    artifact: zip
    draft: false
    prerelease: false
    tag: spinner-v$(appveyor_build_version)
    on:
      branch: master
      appveyor_repo_tag: true