version: '0.2.{build}'

image: Visual Studio 2017

clone_folder: C:\gopath\src\github.com\Ticketmaster\src\spinner
shallow_clone: true

environment:
  GOPATH: C:\gopat

install:
  - set PATH=%GOPATH%\bin;%PATH%
  - ps: Start-FileDownload 'https://github.com/Masterminds/glide/releases/download/v0.12.3/glide-v0.12.3-windows-amd64.zip'
  - ps: Expand-Archive -Path glide-v0.12.3-windows-amd64.zip
  - ps: Copy-Item .\glide-v0.12.3-windows-amd64\windows-amd64\glide.exe .\glide.exe
  - go version
  - go env

branches:
  only:
    - master

#---------------------------------#
#       tests configuration       #
#---------------------------------#

before_test:
  - glide up

test_script:
  - go test --coverprofile=cover.cov

#---------------------------------#
#       build configuration       #
#---------------------------------#

before_build:
  - glide up

build_script:
  - go build  -ldflags "-X main.version=$version" -o "build/spinner$version.exe"

after_build:
  - ps: Compress-Archive -Path "build/spinner$version.exe" -Destination "build/spinner$version.zip"

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:

  # pushing a single file
  - path: build/spinner$(version).zip
    name: zip

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

deploy:
  - provider: GitHub
    release: myproduct-v$(appveyor_build_version)
    description: 'Automated Release'
    artifact: zip
    draft: false
    prerelease: false
    tag: spinner-v$(appveyor_build_version)
    on:
      branch: master
      appveyor_repo_tag: true